project:
  type: book
  execute-dir: file
  output-dir: docs

execute: 
  freeze: auto

book:
  title: "Rockbridge County Zoning Analysis"
  author:
    - name: HousingForward Virginia
      url: https://www.housingforwardva.org
  date: today
  chapters:
    - index.qmd
    - data-collection.qmd
    - doc-review.qmd
    - part: "Rockbridge"
      chapters:
      - current-land-use.qmd
      - existing-zoning.qmd
      - future-land-use.qmd
      - dev-potential.qmd
      #- subdivisions.qmd
      #- entitlements.qmd
    #- part: "Lexington"
    #  chapters: 
    - lexington.qmd
    #- part: "Buena Vista"
    #  chapters: 
    - buena-vista.qmd
#    - summary.qmd
#    - references.qmd

bibliography: references.bib

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
format:
  html:
    theme: lumen
    mainfont: "Open Sans"
    fig-align: left
  # pdf:
  #   documentclass: scrreprt
  #   mainfont: "Open Sans"
  #   fig-pos: "H"
  #   include-in-header:
  #     text: |
  #       \usepackage{float}
  #       \raggedbottom

#comments: 
#  hypothesis: true

