---
engine: knitr
---

## About {.unnumbered}

::: {.content-hidden when-format="html"}

::: {.callout-caution}
### Please note

This document is still under construction. It was last updated `r format(Sys.time(), format = "%B %d, %Y")` at `r format(Sys.time(), "%I:%M %p")`.
:::

::: {.callout-tip}
## How to give interactive feedback

You can highlight and add comments to this website using [hypothesis.is](https://web.hypothes.is/).

1.  Create a [free account](https://web.hypothes.is/start/) with your email address. You do not need to install the browser extension. Be sure to activate your account by clicking the link sent to your email upon registering.
2.  Here, or any other page on this website, open the annotation sidebar by clicking on the little arrow at the top right.
3.  Click "Log in" and enter your credentials when prompted.
4.  You can now select any text on the page to make new annotations or highlights. These will be visible to all viewers.
5.  Clicking on any yellow-highlighted text will reveal comments made by others. You can reply to these annotations.

For more information, see the [Annotation Basics](https://web.hypothes.is/help/annotation-basics/) help page.
:::

:::

This report is an analysis of zoning and land use patterns in Rockbridge County, the City of Lexington, and the City of Buena Vista. This work supports the ongoing [regional housing study](https://www.cspdc.org/programs-services/housing/) that HousingForward Virginia (HFV) and the Virginia Center for Housing Research (VCHR) are completing for the Central Virginia Regional Planning District Commission (CSPDC).

## Objectives

This analysis in this report supports three objectives:

1. To better inform elected officials about housing development patterns, challenges, and opportunities,
2. To attract and solicit developers, and
3. To help apply for grants and other funding opportunities.

## Process

HFV will provide these localities with a comprehensive analysis of their current zoning regimens to determine challenges and opportunities related to housing needs as identified by VCHR.

This work will draw on the following information:

- Current comprehensive plans and related documents,
- Existing land uses by parcel,
- Existing residential and mixed-use zoning districts,
- Future land use categories and map, and
- Current water and sewer system coverage.
